name: flutter_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.0.0 
  file_picker: ^5.0.0
  flutter_animate: ^4.5.0
  percent_indicator: ^4.2.2
  http: ^1.2.2
  webview_flutter: ^4.0.7
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  cloud_firestore: ^5.4.4
  pdf: ^3.10.7
  path_provider: ^2.1.2
  open_file: ^3.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/scan2.gif
    - assets/scanlogo.png
    - assets/user3.jpg
